### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by stevejordan** [neam/php-app-config#1]
Any chance of a tagged release in it's current state? We'd like to use it in a project but would rather not track `dev-develop`.

Thanks.

**Comment by stevejordan** [comment]
Any chance of an update on this? I'd rather not fork it just to add a tag.

Thanks.

**Comment by schmunk42** [comment]
Ping: @motin

**Comment by benlucas** [comment]
:+1:

**Comment by motin** [comment]
Just came back from a country without proper access to the web, I'll tag it tomorrow

**Comment by stevejordan** [comment]
thanks @motin

**Comment by motin** [comment]
Done - https://github.com/neam/php-app-config/releases/tag/1.0.0
Sorry for the delay.
